name: telegram-bot-extra
version: 0.1.0.0
github: "BenefitWizard/telegram-bot-extra"
license: BSD-3-Clause
author: "Aleksandr Tortsev"
maintainer: "ecialo@yandex.ru"
copyright: "2025 Aleksandr Tortsev"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at
  <https://github.com/BenefitWizard/telegram-bot-extra#readme>

dependencies:
  - base >= 4.7 && < 5
  - text
  - telegram-bot-simple
  - telegram-bot-api
  - servant
  - servant-server
  - servant-client
  - attoparsec

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src
  default-extensions:
    - MultiWayIf
    - OverloadedStrings
    - GADTs
    - FlexibleContexts
    - FlexibleInstances
    - TypeFamilies
    - TypeApplications
    - StrictData

tests:
  telegram-bot-extra-test:
    main: Spec.hs
    source-dirs: test
    verbatim:
      build-tool-depends: hspec-discover:hspec-discover == 2.*
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - telegram-bot-extra
      - hspec
      - hspec-wai
      - wai
      - warp
